classdef ObservationList < robotics.ros.Message
    %ObservationList MATLAB implementation of mosaic_msgs/ObservationList
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2015 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mosaic_msgs/ObservationList' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '0153764fa8a79bf6d9098e52bbb7533f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MosaicMsgsObservationClass = robotics.ros.msg.internal.MessageFactory.getClassForType('mosaic_msgs/Observation') % Dispatch to MATLAB class for message type mosaic_msgs/Observation
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Observations
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Observations', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Observations'} % List of non-constant message properties
        ROSPropertyList = {'header', 'observations'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ObservationList(msg)
            %ObservationList Construct the message object ObservationList
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ObservationList', 'header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function observations = get.Observations(obj)
            %get.Observations Get the value for property Observations
            if isempty(obj.Cache.Observations)
                javaArray = obj.JavaMessage.getObservations;
                array = obj.readJavaArray(javaArray, obj.MosaicMsgsObservationClass);
                obj.Cache.Observations = feval(obj.MosaicMsgsObservationClass, array);
            end
            observations = obj.Cache.Observations;
        end
        
        function set.Observations(obj, observations)
            %set.Observations Set the value for property Observations
            if ~isvector(observations) && isempty(observations)
                % Allow empty [] input
                observations = feval([obj.MosaicMsgsObservationClass '.empty'], 0, 1);
            end
            
            validateattributes(observations, {obj.MosaicMsgsObservationClass}, {'vector'}, 'ObservationList', 'observations');
            
            javaArray = obj.JavaMessage.getObservations;
            array = obj.writeJavaArray(observations, javaArray, obj.MosaicMsgsObservationClass);
            obj.JavaMessage.setObservations(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Observations)
                obj.Cache.Observations = [];
                obj.Cache.Observations = obj.Observations;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Observations = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Observations = copy(obj.Observations);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            ObservationsCell = arrayfun(@(x) feval([obj.MosaicMsgsObservationClass '.loadobj'], x), strObj.Observations, 'UniformOutput', false);
            obj.Observations = vertcat(ObservationsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.Observations = arrayfun(@(x) saveobj(x), obj.Observations);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mosaic_msgs.ObservationList.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mosaic_msgs.ObservationList;
            obj.reload(strObj);
        end
    end
end
